controllers/SiteController.php
<?php

namespace app\controllers;

use app\components\Actions;
use app\components\CacheUtil;
use app\models\LoginForm;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\VarDumper;
use yii\web\Controller;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => [
                    'logout',
                    'about',
                    'contact',
                    'login',
                    'info',
                    'random',
                    'bug',
                    'onlyRandom',
                    'puzzle',
                    'player',
                    'menschheit',
                    'kidala',
                    'fwgnl',
                ],
                'rules' => [
                    [
                        'actions' => ['contact','login'],
                        'allow' => false,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['index', 'logout', 'contact', 'info', 'about',],
                        'allow' => true,
//                        'roles' => ['@'],
                    ],
//                    [
//                        'actions' => ['migrate-up', 'migrate-down',],
//                        'allow' => true,
//                        'roles' => ['admin'],
//                    ],
                    [
                        'actions' => [
                            'random',
                            'bug',
                            'onlyRandom',
                            'puzzle',
                            'player',
                            'menschheit',
                            'kidala',
                            'fwgnl',
                        ],
                        'allow' => true,
                        'roles' => ['@', '?'],
                    ],
                    [
                        'actions' => ['login',],
                        'allow' => true,
                        'roles' => ['?'],
                    ],

                ],
            ],
//            'basicAuth' => [
//                'class' => HttpBasicAuth::className(),
//            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionFwgnl()
    {
        return $this->render('fwgnl', []);
    }

    public function actionIndex()
    {
        return $this->render('index', []);
    }

    public function actionMenschheit()
    {
        return CacheUtil::renderCachedData($this,'menschheit', [], 0);
    }

    public function actionKidala()
    {
        return $this->render('kidala', []);
    }

    public function actionOnlyRandom()
    {
        $path = Actions::A_FOLDER . DIRECTORY_SEPARATOR . Actions::getRandomActionName();
        return CacheUtil::renderCachedData($this,$path);
    }

    public function actionBug()
    {
        return $this->redirect(['random', 'id' => Actions::getRandomActionName()]);
    }


//    public function actionMigrateUp()
//    {
//        echo '<pre>';
//        echo 'Выполнение миграции...<br/>';
//        // https://github.com/yiisoft/yii2/issues/1764#issuecomment-42436905
//        $oldApp = \Yii::$app;
//        new \yii\console\Application([
//            'id' => 'Command runner',
//            'basePath' => '@app',
//            'components' => [
//                'db' => $oldApp->db,
//            ],
//        ]);
//        \Yii::$app->runAction('migrate/up', ['migrationPath' => '@app/migrations/', 'interactive' => false]);
//        \Yii::$app = $oldApp;
//        echo '<br/>Говтово!';
//        echo '</pre>';
//    }
//    public function actionMigrateDown()
//    {
//        echo '<pre>';
//        echo 'Откат миграции...<br/>';
//        // https://github.com/yiisoft/yii2/issues/1764#issuecomment-42436905
//        $oldApp = \Yii::$app;
//        new \yii\console\Application([
//            'id' => 'Command runner',
//            'basePath' => '@app',
//            'components' => [
//                'db' => $oldApp->db,
//            ],
//        ]);
//        \Yii::$app->runAction('migrate/down', ['migrationPath' => '@app/migrations/', 'interactive' => false]);
//        \Yii::$app = $oldApp;
//        echo '<br/>Готово!';
//        echo '</pre>';
//    }


    public function actionInfo()
    {
        \Yii::$app->response->format = \yii\web\Response::FORMAT_XML;
        return [
            'message' => 'hello world',
            'code' => 100,
        ];
    }


    public function actionPuzzle()
    {
        return $this->render('puzzle');
    }


    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

//    public function actionContact()
//    {
//        $model = new ContactForm();
//        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
//            Yii::$app->session->setFlash('contactFormSubmitted');
//
//            return $this->refresh();
//        }
//        return $this->render('contact', [
//            'model' => $model,
//        ]);
//    }

    public function actionAbout()
    {
        return CacheUtil::renderCachedData($this,'about', [], 0);
    }

    public function actionPlayer()
    {
        return $this->render('player');
    }

    public function actionRandom($id){
        $path = Actions::A_FOLDER . DIRECTORY_SEPARATOR . $id;
        return CacheUtil::renderCachedData($this,$path);
    }
}

controllers/UserController.php
<?php

namespace app\controllers;

use app\models\search\UserSearch;
use app\models\User;
use Yii;
use yii\db\Exception;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\web\Controller;
use yii\web\ForbiddenHttpException;
use yii\web\NotFoundHttpException;

/**
 * UserController implements the CRUD actions for User model.
 */
class UserController extends Controller
{

//    public $layout = 'user_lk';

    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['index','create','update','view','delete','registration','changeUsername','changePassword','confirm',],
                'rules' => [
                    [
                        'actions' => ['index','create','update','view','delete',],
                        'allow' => true,
                        'roles' => ['admin',],
                    ],
                    [
                        'actions' => [
                            'changeUsername',
                            'changePassword',
                        ],
                        'allow' => true,
                        'roles' => ['user','admin'],
                    ],
                    [
                        'actions' => ['registration','confirm'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['post',],
                ],
            ],
        ];
    }


    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }



    public function actionChangePassword(){
        $model = $this->findModel(Yii::$app->user->getId());
        $model_new1 = new User();
        $model_new2 = new User();
        $post = Yii::$app->request->post('User');
        $p = isset($post['p']['password'])?$post['p']['password']:'';
        $p1 = isset($post['p1']['password'])?$post['p1']['password']:'';
        $p2 = isset($post['p2']['password'])?$post['p2']['password']:'';
        $model_new1->password = $p1;
        $model_new2->password = $p2;
        $session = Yii::$app->session;
        if ($p!='' and $p1!='' and $p2!=''){
            if($p1==$p2){
                if(@md5(@md5($p)) == $model->password){
                    $n_pass = @md5(@md5($p1));
                    if($n_pass == $model->password) {
                        $session->setFlash('error_msg', 'Придумайте другой пароль');
                    }else if($n_pass != $model->password){
                        $model->password = $n_pass;
                        $model->save(false);
                        $session->setFlash('success_msg', 'Вы успешно изменили пароль');
                        $model->password = $model_new1->password = $model_new2->password = '';
                        return $this->render('user_password',
                            [
                                'model' => $model,
                                'model_new1' => $model_new1,
                                'model_new2' => $model_new2,
                            ]
                        );
                    }
                }else{
                    $session->setFlash('error_msg', 'Неверно указан старый пароль');
                }
            }else{
                $session->setFlash('error_msg', 'Новые пароли не совпадают');
            }
        }else {
            if(($p!='' and ($p1=='' or $p2=='')) or ($p1!='' and ($p=='' or $p2=='')) or ($p2!='' and ($p=='' or $p1==''))) {
                $session->setFlash('error_msg', 'Необходимо заполнить все поля');
            }
        }
        $model->password = $p;
        return $this->render('user_password', [
            'model' => $model,
            'model_new1' => $model_new1,
            'model_new2' => $model_new2,
        ]);
    }


    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     */
//    public function actionView($id)
//    {
//            return $this->render('view', [
//                'model' => $this->findModel($id),
//            ]);
//    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = User::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */


    public function actionCreate()
    {
        $model = new User();
        if ($model->load(Yii::$app->request->post())) {
            $transaction = Yii::$app->db->beginTransaction();
            try{
                $userRole = Yii::$app->authManager->getRole($_REQUEST['user_role']);
                Yii::$app->authManager->assign($userRole, $model->getId());
                $transaction->commit();
            }catch (Exception $e){
                $transaction->rollBack();
                throw $e;
            }

            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    public function actionRegistration()
    {
        $post = Yii::$app->request->post();
        $model = new User();
        $model->load($post);
        $model->password = \Yii::$app->security->generateRandomString(6);
        $model->username = $model->email;
        if($model->validate()){
            $transaction = Yii::$app->db->beginTransaction();
            try{
                $model->save(false);
                $userRole = Yii::$app->authManager->getRole('user');
                Yii::$app->authManager->assign($userRole, $model->getId());
                $body =  Html::a('Подтвердить регистрацию',
                    Url::to(
                        ['user/confirm',
                            'a'=>$model->getId(),
                            'b'=>$model->getAuthKey(),
                        ],true
                    )
                );
                Yii::$app->mailer->compose()
                    ->setTo($model->email)
                    ->setFrom(Yii::$app->params['adminEmail'])
                    ->setSubject("Регистрация")
                    ->setHtmlBody($body)
                    ->send();
                $transaction->commit();
            }catch (Exception $e){
                $transaction->rollBack();
                throw $e;
            }
            return $this->render('registration_success', ['model' => $model]);
        } else {
            return $this->render('registration', [
                'model' => $model,
            ]);
        }
    }

    public function actionConfirm($a, $b){
        $model=$this->findModel($a);
        if($model->getAuthKey() === $b){
            $model->password = \Yii::$app->security->generateRandomString(6);
            $pass = $model->password;
            $model->authKey = \Yii::$app->security->generateRandomString();
            $transaction = Yii::$app->db->beginTransaction();
            try{
                $model->password =@md5(@md5($model->password));
                $model->save(false);
                $body =  'Регистрация прошла успешно. Ваш пароль для входа"'.$pass.'"';
                Yii::$app->mailer->compose()
                    ->setTo($model->email)
                    ->setFrom(Yii::$app->params['adminEmail'])
                    ->setSubject("Регистрация подтверждена. Пароль для входа.")
                    ->setHtmlBody($body)
                    ->send();
                $transaction->commit();
                return $this->redirect(['site/login']);
            }catch (Exception $e){
                $transaction->rollBack();
                throw $e;
            }
        }
        return $this->render('confirm-to-late');
    }

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionChangeUsername()
    {
        $model = $this->findModel(Yii::$app->user->getId());
        if ($model->load(Yii::$app->request->post()) && $model->save(true,['username'])) {
            return $this->redirect(['/site/index']);
        } else {
            return $this->render('user_name', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        if (\Yii::$app->user->can('admin') or \Yii::$app->user->can('updateSelfUser', ['user_id'=>$id])) {
            $this->findModel($id)->delete();
            return $this->redirect(['index']);

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\assets\AppAsset;
use app\assets\FontAwesomeAsset;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;
use yii\helpers\Url;

FontAwesomeAsset::register($this);
AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="description" content="Сайт ни о чем.">
    <meta name="keywords"
          content="логика, спор, искусство, диалектика, вселенная, силлогизм, гроб, дельфин, летов, гражданская, оборона,"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ?>
<div id="scroll-top" onclick="scrollA();return false;">
    <div class="scroll-top"></div>
</div>
<div class="wrap">
    <?= Html::a('<i class="fa fa-bug fa-4x" aria-hidden="true"></i>', Url::to(['site/only-random']),
        ['class' => 'main_bug']); ?>
    <?php
    NavBar::begin([
        'brandLabel' => 'Мутабор',
        'brandUrl' => Yii::$app->homeUrl,
        'options' => [
            'class' => 'navbar-inverse navbar-fixed-top',
        ],
    ]);

    echo Nav::widget([
        'options' => ['class' => 'navbar-nav navbar-right'],
        'encodeLabels' => false,
        'items' => [
//            ['label' => 'Регистрация', 'url' => ['/user/registration'], 'visible'=> Yii::$app->user->isGuest,],
//            Yii::$app->user->isGuest ?
//                ['label' => 'Login', 'url' => ['/site/login']] :
//                [
//                    'label' => 'Logout (' . Yii::$app->user->identity->username . ')',
//                    'url' => ['/site/logout'],
//                    'linkOptions' => ['data-method' => 'post'],
//                ],
            ['label' => '<i class="fa fa-cube" aria-hidden="true"></i>', 'url' => ['/site/kidala'],],
            ['label' => '<i class="fa fa-paw" aria-hidden="true"></i>', 'url' => ['/site/menschheit'],],
            ['label' => '<i class="fa fa-space-shuttle" aria-hidden="true"></i>', 'url' => ['/site/player'],],
            ['label' => '<i class="fa fa-diamond" aria-hidden="true"></i>', 'url' => ['/site/fwgnl'],],
            ['label' => '<i class="fa fa-object-group" aria-hidden="true"></i>', 'url' => ['/logic/uchebnik'],],
            ['label' => '<i class="fa fa-fire" aria-hidden="true"></i>', 'url' => ['/logic/spor'],],
//            ['label' => '<i class="fa fa-child" aria-hidden="true"></i>', 'url' => ['/logic/spor'],],

//            ['label' => 'ЛК', 'url' => ['/user/settings'], 'visible'=> !Yii::$app->user->isGuest,],

            ['label' => '<i class="fa fa-american-sign-language-interpreting" aria-hidden="true"></i>', 'url' => ['/logic/sillogism'],],
//            ['label' => '<i class="fa fa-bug" aria-hidden="true"></i>', 'url' => ['/site/bug'],],
            ['label' => '<i class="fa fa-bug" aria-hidden="true"></i>', 'url' => ['/site/only-random'],],
//            ['label' => '<i class="fa fa-bomb" aria-hidden="true"></i>', 'url' => ['/site/random','id'=>'latin_aphorisms'],],
//            ['label' => '<i class="fa fa-graduation-cap" aria-hidden="true"></i>', 'url' => ['/site/random','id'=>'latin_aphorisms'],],
//            ['label' => '<i class="fa fa-fire" aria-hidden="true"></i>', 'url' => ['/site/random','id'=>'latin_aphorisms'],],


            ['label' => '<i class="fa fa-puzzle-piece" aria-hidden="true"></i>', 'url' => ['/site/puzzle'],],
            [
                'label' => '<i class="fa fa-braille" aria-hidden="true"></i>',
                'url' => ['/site/random', 'id' => 'latin_aphorisms'],
            ],
//            ['label' => 'Ингридиенты', 'url' => [''],'visible'=> Yii::$app->user->can('admin'),
//                'items' => [
//                    ['label' => 'Добавить', 'url' => ['/nsign/component/create']],
//                    ['label' => 'Активация/Деактивация', 'url' => ['/nsign/component/view-all']],
//                    ['label' => 'Таблица/поиск', 'url' => ['/nsign/component/index']],
//                ]
//            ],
//            ['label' => 'Блюда', 'url' => [''],'visible'=> Yii::$app->user->can('admin'),
//                'items' => [
//                    ['label' => 'Добавить', 'url' => ['/nsign/course/create']],
//                    ['label' => 'Посмотреть все', 'url' => ['/nsign/course/index']],
//                ]
//            ],
//            ['label' => 'Поиск блюд', 'url' => ['/nsign/course/filt'], 'visible'=> !Yii::$app->user->isGuest],
//            ['label' => 'Миграции', 'url' => [''],'visible'=> Yii::$app->user->can('admin'),
//                'items' => [
//                    ['label' => 'Накатить', 'url' => ['/site/migrate-up']],
//                    ['label' => 'Откатить', 'url' => ['/site/migrate-down']],
//                ]
//            ],
//            ['label' => '<i class="fa fa-key" aria-hidden="true"></i>', 'url' => ['/site/contact'],],
            ['label' => 'О', 'url' => ['/site/about'],],

        ],
    ]);
    NavBar::end();
    ?>

    <div class="container">
        <?= $content ?>
    </div>
</div>

<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; mutabor <?= date('Y') ?></p>

        <p class="pull-left">

        </p>

        <p class="pull-left">
            <!-- counter.1gb.ru -->
            <script language="javascript" type="text/javascript">
                cgb_js = "1.0";
                cgb_r = "" + Math.random() + "&r=" +
                escape(document.referrer) + "&pg=" +
                escape(window.location.href);
                document.cookie = "rqbct=1; path=/";
                cgb_r += "&c=" +
                (document.cookie ? "Y" : "N");
            </script>
            <script language="javascript1.1" type="text/javascript">
                cgb_js = "1.1";
                cgb_r += "&j=" +
                (navigator.javaEnabled() ? "Y" : "N")</script>
            <script language="javascript1.2" type="text/javascript">
                cgb_js = "1.2";
                cgb_r += "&wh=" + screen.width +
                'x' + screen.height + "&px=" +
                (((navigator.appName.substring(0, 3) == "Mic")) ?
                    screen.colorDepth : screen.pixelDepth)</script>
            <script language="javascript1.3" type="text/javascript">
                cgb_js = "1.3"</script>
            <script language="javascript"
                    type="text/javascript">cgb_r += "&js=" + cgb_js;
                document.write("<a href='http://www.1gb.ru?cnt=92873'>" +
                "<img src='http://counter.1gb.ru/cnt.aspx?" +
                "u=92873&" + cgb_r +
                "&' border=0 width=88 height=31 " +
                "alt='1Gb.ru counter'><\/a>")</script>
        <noscript><a href='http://www.1gb.ru?cnt=92873'>
                <img src="http://counter.1gb.ru/cnt.aspx?u=92873"
                     border=0 width="88" height="31" alt="1Gb.ru counter"></a>
        </noscript>
        <!-- /counter.1gb.ru -->
        </p>
        <p>
            <!-- Yandex.Metrika informer -->
            <a href="https://metrika.yandex.ru/stat/?id=37956070&amp;from=informer"
               target="_blank" rel="nofollow"><img
                    src="https://informer.yandex.ru/informer/37956070/3_1_FFFFFFFF_EFEFEFFF_0_pageviews"
                    style="width:88px; height:31px; border:0;" alt="Яндекс.Метрика"
                    title="Яндекс.Метрика: данные за сегодня (просмотры, визиты и уникальные посетители)"
                    onclick="try{Ya.Metrika.informer({i:this,id:37956070,lang:'ru'});return false}catch(e){}"/></a>
            <!-- /Yandex.Metrika informer -->

            <!-- Yandex.Metrika counter -->
            <script type="text/javascript">
                (function (d, w, c) {
                    (w[c] = w[c] || []).push(function () {
                        try {
                            w.yaCounter37956070 = new Ya.Metrika({
                                id: 37956070,
                                clickmap: true,
                                trackLinks: true,
                                accurateTrackBounce: true,
                                webvisor: true
                            });
                        } catch (e) {
                        }
                    });

                    var n = d.getElementsByTagName("script")[0],
                        s = d.createElement("script"),
                        f = function () {
                            n.parentNode.insertBefore(s, n);
                        };
                    s.type = "text/javascript";
                    s.async = true;
                    s.src = "https://mc.yandex.ru/metrika/watch.js";

                    if (w.opera == "[object Opera]") {
                        d.addEventListener("DOMContentLoaded", f, false);
                    } else {
                        f();
                    }
                })(document, window, "yandex_metrika_callbacks");
            </script>
        <noscript>
            <div><img src="https://mc.yandex.ru/watch/37956070" style="position:absolute; left:-9999px;" alt=""/></div>
        </noscript>
        <!-- /Yandex.Metrika counter -->
        </p>

    </div>
</footer>

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

views/layouts/user_lk.php
<?php

/* @var $this \yii\web\View */
use yii\helpers\Html;

/* @var $content string */
//echo Url::to(['post/index']);
?>
<!--
TABLE TO FIX IE/6 ISSUE
The one where 23% margin + 100% table = 123% in IE6 o_O
-->

<table cellspacing="0" cellpadding="0" width='100%'>
    <tr>
        <td id="ucpmenu" valign="top">
            <div class='maintitle'>Меню</div>
            <!--IBF.TSLLINKS-->
            <!-- Topic Tracker -->
            <div class='pformstrip'>Мои подписки</div>
            <p>
                &middot; <?= Html::a('Темы',['user/themes']);?><br />
                &middot; <?= Html::a('Форумы',['user/forums']);?><br />
            </p>
            <!-- Profile -->
            <div class='pformstrip'>Ваш профиль</div>
            <p>
                &middot; <?= Html::a('Личные данные',['user/change-info']);?><br />
                &middot; <?= Html::a('Редактировать подпись',['user/change-subscribtion']);?><br />
                &middot; <?= Html::a('Настройки аватара',['user/change-avatar']);?><br />
                &middot; <?= Html::a('Изменить фотографию',['user/change-photo']);?><br />
            </p>
            <!-- Options -->
            <div class='pformstrip'>Настройки</div>
            <p>
                <!--IBF.OPTION_LINKS-->
                &middot; <?= Html::a('Настройки e-mail',['user/change-email-settings']);?><br />
                &middot; <?= Html::a('Настройки форума',['user/change-forum-settings']);?><br />
                &middot; <?= Html::a('Изменить e-mail адрес',['user/change-email']);?><br />
                &middot; <?= Html::a('Изменить пароль',['user/change-password']);?><br />
            </p>
        </td>
        <td style='padding:2px'><!-- --></td>
        <!-- Start main CP area -->
        <td id="ucpcontent" valign="top">
            <div class="maintitle">Добро пожаловать в Вашу Панель управления </div>
            <?php
                echo $content;
            ?>
        </td>

    </tr>
</table>